title: "Paul M Furley, developer"
url: "https://www.paulfurley.com"
gems:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog_post"
      author: "Paul M Furley"

permalink: /:title
markdown: kramdown
kramdown:
  input: GFM

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - _sass
  - .sass-cache
