#!/bin/sh -eux

THIS_SCRIPT=$0
THIS_DIR=$(dirname ${THIS_SCRIPT}£)

TMP_DIR=$(mktemp -d --suffix .site)

git --work-tree=${TMP_DIR} checkout master -- .

cd "${TMP_DIR}"
make


sleep 5s

rsync -avr --delete-after --delete-excluded ${TMP_DIR}/_site/ paulfurley@www.paulfurley.com:/var/www/www.paulfurley.com


echo rm -rf "${TMP_DIR}"
