#!/bin/sh -eux

THIS_SCRIPT=$0
THIS_DIR=$(dirname ${THIS_SCRIPT})
REPO_DIR=${THIS_DIR}/..

TMP_REPO_DIR=$(mktemp -d --suffix .site)

REMOTE=$(git remote get-url origin)

git clone ${REPO_DIR} "${TMP_REPO_DIR}"
git clone ${REPO_DIR} -b build "${TMP_REPO_DIR}/_site"

cd "${TMP_REPO_DIR}"
make

cd _site
git add --all .
git commit -m "Autocommit from Jekyll build"

echo "# pushing to github build branch"
git remote add github "$REMOTE"
git push -f github build:build


echo rm -rf "${TMP_REPO_DIR}"
